---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: debian-7.4

suites:
  - name: debnetwork
    run_list:
      - recipe[fake::default]
    attributes:
      debnetwork:
        postrouting_rules: [
          '-s 10.10.10.10 -j MASQUERADE'
        ]
        forward_rules: [
          '-m state --state RELATED,ESTABLISHED -j ACCEPT'
        ]
